// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that determines winning lottery tickets.
 *
 * - determineWinners - A function that takes winning numbers and ticket details
 *   and identifies winning tickets.
 * - DetermineWinnersInput - The input type for the determineWinners function.
 * - DetermineWinnersOutput - The return type for the determineWinners function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetermineWinnersInputSchema = z.object({
  winningNumbers: z
    .string()
    .describe('The winning numbers for the lottery draw (e.g., \'12 34 56\').'),
  ticketDetails: z
    .string()
    .describe(
      'Details of all tickets sold for the draw, including ticket number and associated user IDs.'
    ),
});
export type DetermineWinnersInput = z.infer<typeof DetermineWinnersInputSchema>;

const DetermineWinnersOutputSchema = z.object({
  winningTicketIds: z
    .array(z.string())
    .describe('An array of ticket IDs that are identified as winners.'),
});
export type DetermineWinnersOutput = z.infer<typeof DetermineWinnersOutputSchema>;

export async function determineWinners(input: DetermineWinnersInput): Promise<DetermineWinnersOutput> {
  return determineWinnersFlow(input);
}

const determineWinnersPrompt = ai.definePrompt({
  name: 'determineWinnersPrompt',
  input: {schema: DetermineWinnersInputSchema},
  output: {schema: DetermineWinnersOutputSchema},
  prompt: `You are an expert lottery analyst. Your task is to analyze lottery ticket data and identify the winning tickets based on the provided winning numbers.

Winning Numbers: {{{winningNumbers}}}

Ticket Details: {{{ticketDetails}}}

Analyze the ticket details and identify the tickets that match the winning numbers. Return ONLY the array of the winning ticket IDs.
`,
});

const determineWinnersFlow = ai.defineFlow(
  {
    name: 'determineWinnersFlow',
    inputSchema: DetermineWinnersInputSchema,
    outputSchema: DetermineWinnersOutputSchema,
  },
  async input => {
    const {output} = await determineWinnersPrompt(input);
    return output!;
  }
);
